Makefile: added check for wrpc-sw path sanity

diff --git a/arch-wrpc/Makefile b/arch-wrpc/Makefile
--- a/arch-wrpc/Makefile
+++ b/arch-wrpc/Makefile
@@ -30,3 +30,11 @@ TIME := wrpc
 include time-wrpc/Makefile
 
 $(TARGET).o: $(LIBARCH)
+
+$(OBJ-y): wrpcsw_root_check
+
+wrpcsw_root_check:
+	if ! [ -e "$(WRPCSW_ROOT)/include/wrc.h" ]; then\
+		echo "Error: WRPCSW_ROOT: can't find $(WRPCSW_ROOT)/include/wrc.h" >&2;\
+		exit 1;\
+	fi
